name: Docker Build and Scan

on:
  push:
    branches:
      - master
    paths-ignore:
      - .github/**
      - .gitignore
      - LICENSE
      - README.md
      - renovate.json

  release:
    types: [published]

  # Run tests for any PRs.
  pull_request:

  # Manual run
  workflow_dispatch:

env:
  IMAGE_NAME: prime-pipeline

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v5

      - name: Build Docker image locally
        run: |
          if [ -f docker-compose.test.yml ]; then
            docker-compose --file docker-compose.test.yml build
            docker-compose --file docker-compose.test.yml run sut
          else
            docker build . --file Dockerfile --tag localbuild/testimage:latest
          fi

      - name: Run the Anchore scan action itself with GitHub Advanced Security code scanning integration enabled
        uses: anchore/scan-action@v7
        id: scan
        with:
          image: "localbuild/testimage:latest"
          fail-build: false
          severity-cutoff: high

      - name: Upload Anchore Scan Report
        uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: ${{ steps.scan.outputs.sarif }}

      - name: Create software bill of materials when releasing
        uses: anchore/sbom-action@v0
        with:
          image: localbuild/testimage:latest
          artifact-name: sbom.spdx
        if: github.event_name == 'release'
